name: Deploy to GCP

on:
  push:
    branches:
      - main # Push or Merge to main will invoke this action

jobs:
  Terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Terraform Init
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform init

      - name: Terraform Validate
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform validate

      - name: Terraform Plan
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} # Credentials are stored as a secret in the GitHub repository

      - name: Terraform Apply
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo 
          terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} # Credentials are stored as a secret in the GitHub repository
