name: Deploy to GCP

on:
  push:
    branches:
      - main 

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.commit.outputs.skip }}
    steps:
      - name: Check Commit
        id: commit
        run: |
          message=$(git log --format=%B -n 1 ${{ github.event.after }})
          if [[ "$message" == *"codefix"* ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi
  Terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Terraform Init
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform init

      - name: Terraform Validate
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform validate

      - name: Terraform Plan
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo 
          terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: GFT Auto Doc
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
            gft autodoc --config_path /Users/pgsp/POC/gft-aimpact-cli.uk/configfiles/autodoc/config-sample.yaml