name: Deploy to GCP

on:
  push:
    branches:
      - main 

jobs:
  Terraform:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, 'deploy')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Terraform Init
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform init

      - name: Terraform Validate
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform validate

      - name: Terraform Plan
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Apply
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo 
          terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  AutoDoc:
    runs-on: self-hosted
    if: contains(github.event.head_commit.message, 'deploy')
    steps:
      - name: GFT Auto Doc
        run: |
          cd /Users/pgsp/POC/gcs-ai-demo
          gft autodoc --config_path /Users/pgsp/POC/gft-aimpact-cli.uk/configfiles/autodoc/config-sample.yaml