name: Review and Fix Code

on:
  push:
    branches-ignore:
      - main # Any pushes to main are ignored as code will have been reviewed and fixed before merging.
      - '*correction*' # Any pushes to branches with 'correction' in the name are ignored as code will have been reviewed and fixed before merging.

jobs:
  GFT-AI-Impact-Code-Review-and-Fix:
    runs-on: self-hosted # use self-hosted as we do not have access to GitHub Actions hosted runners
        if: contains(github.event.head_commit.message, 'go')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: GFT AImpact code review and fix
        run: |
          cd /Users/pgsp/POC/gft-aimpact-cli.uk
          gft codefix --config_path configfiles/fix/config-sample.yaml
      
        

