name: Review and Fix Code

on:
  push:
    branches-ignore:
      - '*correction*'
  

jobs:
  GFT-AI-Impact-Code-Review-and-Fix:
    runs-on: self-hosted # use self-hosted as we do not have access to GitHub Actions hosted runners
    if: contains(github.event.head_commit.message, 'fixcode')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: List files
        run: ls -R

      - name: GFT AImpact code review and fix
        run: |
          cd /Users/pgsp/POC/gft-aimpact-cli.uk
          gft codefix --config_path configfiles/fix/config-sample.yaml
      
        

